# Generated by Django 3.2.13 on 2022-04-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('provider', 'Provider'), ('customer', 'Customer'), ('bank', 'Bank')], default='customer', max_length=10)),
            ],
        ),
    ]
