# Generated by Django 3.2.13 on 2022-04-22 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_loancustomer_loantermcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantermcustomer',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
