# Generated by Django 3.2.13 on 2022-04-22 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_loantermcustomer_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantermcustomer',
            name='interest',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
