# Generated by Django 3.2.13 on 2022-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_loantermcustomer_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancustomer',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
