# Generated by Django 3.2.13 on 2022-04-22 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_loancustomer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancustomer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
